services:
  node:
    build: .
    container_name: hlm_fe_node
    tty: true
    ports:
      - 46500:${APP_PORT}
    volumes:
      - ./:/work
      - /work/node_modules
    networks:
      - hlm_network

networks:
  hlm_network:
    external: true